### ISSUE TITLE
session is destroyed on return

### ISSUE THREAD

**Issue by mestia** [PerlDancer/Dancer2-Session-Cookie#12]
I run into a strange problem with Dancer2::Session::Cookie, the code below simulates the problem.
It seems that session is destroyed on redirect.

The same code works correctly with Dancer2::Session::YAML - the session survives the return.
To login, please navigate to /login route - default for Dancer2::Plugin::Auth::Extensible.

Also if I uncomment this line `my @roles = user_roles() if logged_in_user();`
for the second route the session works as expected - survives the return.

I used Starman to launch the application: 

```
plackup -E development -s Starman --workers=5 --host 127.0.0.1 -a bin/app.psgi
```

versions: Dancer2 0.160003, Dancer2::Session::Cookie 0.006-1

thank you !

the code: 
`dancer -a MyWeb::App`

cat lib/MyWeb/App.pm

```
package MyWeb::App;
use Dancer2;
use Dancer2::Plugin::Auth::Extensible;

our $VERSION = '0.1';

hook before_template => sub {
    my $tokens = shift;
    if ( user_has_role('Developer') ) {
        $tokens->{'admin_mode'}  = 'yes';
    } else {
        $tokens->{'admin_mode'}  = undef;
    }
};

get '/' => sub {
    my $images = getImages('/tmp');
    my @roles = user_roles() if logged_in_user();
    my $str = join(',',@roles);
    template 'listtmp', {
            content => $images,
            roles => $str,
        };
};

get qr{\/?([\w\d\-\_\s]*)$}ixms => sub {
    my ($route) = splat;
#    my @roles = user_roles() if logged_in_user();
#    my $str = join(',',@roles);
#    return "roles $str";
    return redirect '/';
};

sub getImages {
    my ($dir) = @_;
    opendir( my $dh,"$dir" ) or return false;
        my  @files = grep { !/^\./ } readdir($dh);
        close $dh;
    return \@files || false;
}
true;
```

cat views/listtmp.tt

```

<% IF admin_mode %>

    <% FOREACH file IN content.sort %>
        <a href="<% file %>"> <% file %> </a><br>
    <% END %>

<% END %>

<h1> roles: <% roles %> </h1>
```

 egrep -v "^$|^#" config.yml

```
appname: "MyWeb::App"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
session: Cookie
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
  session:
    Cookie:
      secret_key: outhorsesessionstaple
      default_duration: 604800
plugins:
  Auth::Extensible:
    realms:
      config:
          provider: Config
          users:
              - user: test
                pass: beer
                roles:
                  - Developer
                  - Manager
                  - BeerDrinker
```
