### ISSUE TITLE
How to set  cookie_duration ?

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2-Session-Cookie#14]
The docs mention `cookie_duration` but it is unclear to me how to use it.
Calling `cookie_duration(20)` in a route was met with complains of not existing function.
Calling `session cookie_duration => 20` in a route did not seem to have any impact.

**Comment by LittleFox94** [comment]
You can set in the configuration file of your dancer2 app:

```yml
engines:
  session:
    Cookie:
      default_duration: 7200
```
