### ISSUE TITLE
Missing required arguments: secret_key

### ISSUE THREAD

**Issue by realflash** [PerlDancer/Dancer2-Session-Cookie#18]
I'd like to use this module. When I select it as the session engine, I get

`Missing required arguments: secret_key at /usr/local/share/perl/5.18.2/Dancer2/Core/Factory.pm line 19.`

Here's the relevant part of my config.yml:

```
session: Cookie
engines:
  session:
    Simple:
      cookie_name: myapp.session
    Cookie:
      secret_key: ashortkey
      default_duration: 604800
      with_request_address: 0
```

I have confirmed that there are six spaces at the beginning of the line containing `secret_key`. All the other lines have the right number of spaces too. All the other directives in my config.yml are taking effect fine - custom variables, changing the template engine, layout etc., so I know the file is being read and parsed OK.  If I switch `session: Cookie` to `session: Simple`, sessions work fine - I can save and restore data from the session without problem. It seems to make no difference whether Simple: is defined as an engine or not. 

From some code browsing I infer that it is probably Moo complaining on instantiation of a Dancer2::Session::Cookie object that the argument is missing. Can you offer any suggestions, please?

v0.008 installed via cpanm successfully first time.
